# Config file for (H)-BPTT algorithm.
num_steps: 3
num_samples: 2
num_iter: 1
train_frequency: 1
num_rollouts: 0
lambda: 0.1  # entropy regularization coefficient.
eta: 0.2  # entropy regularization coefficient.
entropy_regularization: False  # Have it as a constraint.
kl_mean: 0.01
kl_var: 0.0001
kl_regularization: False
calibrate: False
model_learn_exploration_episodes: 5
exploration_episodes: 10
